# Generated by Django 5.0.6 on 2024-07-03 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('CardID', models.AutoField(primary_key=True, serialize=False)),
                ('CardNumber', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('iat', models.DateTimeField()),
                ('exp', models.DateTimeField()),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('CardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfc_access.nfccard')),
            ],
        ),
        migrations.AddField(
            model_name='nfccard',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfc_access.user'),
        ),
    ]
